---
# Create docker directory
- name: Create docker directory
  file: path={{ playbook_dir }}/docker/docker-babelnet-hujo state=directory
  tags:
    - configuration
  
# Build and push image
- name: Create babelnet-hujo Dockerfile
  template: src=babelnet-hujo-dockerfile.j2 dest={{ playbook_dir }}/docker/docker-babelnet-hujo/Dockerfile
  tags:
    - configuration

- name: Build babelnet-hujo image
  docker_image: docker_url=tcp://127.0.0.1:2375 path="{{ playbook_dir }}/docker/docker-babelnet-hujo" name="{{ babelnethujo_image_name }}" state="build"
  tags:
    - docker
    - docker_build

- name: Push babelnet-hujo image to repo
  shell: "docker push {{ babelnethujo_image_name }}"
  tags:
    - docker
    - docker_push

# Create required fleet unit files
- name: Create Units directory
  file: path={{ playbook_dir }}/units state=directory
  tags:
    - configuration

- name: Create babelnet-hujo Units
  template: src=babelnet-hujo.x.service.j2 dest={{ playbook_dir }}/units/babelnet-hujo.1.service
  tags:
    - configuration

# Submit units to fleet
- name: Submit babelnet-hujo units
  shell: fleetctl --tunnel {{ fleet_endpoint }} submit {{ playbook_dir }}/units/babelnet-hujo.1.service
  tags:
    - fleet
    - fleet_submit

# Start units via fleet
- name: Start babelnet-hujo units
  shell: sleep 5 && fleetctl --tunnel {{ fleet_endpoint }} start {{ playbook_dir }}/units/babelnet-hujo.1.service
  tags:
    - fleet
    - fleet_start
