---
- name: Build zookeeper image
  docker_image: docker_url=tcp://127.0.0.1:2375 path="roles/ansible-coreos-zookeeper/docker/docker-zookeeper" name="{{ zookeeper_image_name }}" state="build"
  tags:
    - docker
    - docker_build

- name: Push zookeeper image to repo
  shell: "docker push {{ zookeeper_image_name }}"
  tags:
    - docker
    - docker_push

- name: Create Units directory
  file: path={{ playbook_dir }}/units state=directory
  tags:
    - configuration

- name: Gather fleet machines info
  get_coreos_machines: tunnel={{ fleet_endpoint }}
  register: fleetctl_hosts
  tags:
    - configuration

- name: Find zookeeper hosts
  get_zookeeper_servers: number={{ zookeeper_instances_number }}  hosts='{{ fleetctl_hosts.stdout }}'
  register: zookeeper_hosts
  tags:
    - configuration

- name: Create Zookeeper Units
  template: src=zookeeper.x.service.j2 dest={{ playbook_dir }}/units/zookeeper.{{ item }}.service
  with_sequence: count={{ zookeeper_instances_number }}
  tags:
    - configuration

- name: Create Zookeeper Sidekick Units
  template: src=zookeepersidekick.x.service.j2 dest={{ playbook_dir }}/units/zookeepersidekick.{{ item }}.service
  with_sequence: count={{ zookeeper_instances_number }}
  tags:
    - configuration

# Submit Units

- name: Submit Zookeeper units
  shell: fleetctl --tunnel {{ fleet_endpoint }} submit {{ playbook_dir }}/units/zookeeper.{{ item }}.service
  with_sequence: count={{ zookeeper_instances_number }}
  tags:
    - fleet
    - fleet_submit

- name: Submit Zookeeper Sidekick units
  shell: fleetctl --tunnel {{ fleet_endpoint }} submit {{ playbook_dir }}/units/zookeepersidekick.{{ item }}.service
  with_sequence: count={{ zookeeper_instances_number }}
  tags:
    - fleet
    - fleet_submit

# Start Units
- name: Start Zookeeper units
  shell: sleep 5 && fleetctl --tunnel {{ fleet_endpoint }} start {{ playbook_dir }}units/zookeeper.{{ item }}.service
  with_sequence: count={{ zookeeper_instances_number }}
  tags:
    - fleet
    - fleet_start

- name: Start Zookeeper Sidekick units
  shell: sleep 5 && fleetctl --tunnel {{ fleet_endpoint }} start {{ playbook_dir }}units/zookeepersidekick.{{ item }}.service
  with_sequence: count={{ zookeeper_instances_number }}
  tags:
    - fleet
    - fleet_start
